# Cooker (format "rg8-shade-coverage"): pack an ORDERED set of grayscale+alpha PNGs into
# two parallel single-byte arrays -- SHADE (Rec.601 luminance) and COVERAGE (alpha) --
# emitted as a C++ header of raw bytes, uploaded at runtime as an R8G8 texture (R=shade,
# G=coverage). Game-agnostic: all names (namespace, size/array identifiers) and the source
# order come from the caller (derived from the gameplay code's LUR_COOK declaration), so
# this file contains no game-specific terminology.
#
# Dot-sourced by Cook/Cook.ps1, which decides WHEN to run it and stamps the source hash.
Add-Type -AssemblyName System.Drawing

# PNG channel layout from the IHDR colour-type byte (0=gray 2=RGB 3=palette 4=gray+alpha 6=RGBA).
function Get-PngInfo([string]$png) {
    $head = [System.IO.File]::ReadAllBytes($png) | Select-Object -First 26
    $sig = 137,80,78,71,13,10,26,10
    for ($i = 0; $i -lt 8; $i++) { if ($head[$i] -ne $sig[$i]) { throw "$png is not a PNG (bad signature)." } }
    switch ($head[25]) {
        0       { return @{ Channels = 1; HasAlpha = $false } }
        2       { return @{ Channels = 3; HasAlpha = $false } }
        4       { return @{ Channels = 2; HasAlpha = $true  } }
        6       { return @{ Channels = 4; HasAlpha = $true  } }
        default { throw "$png uses unsupported PNG colour type $($head[25]); export grayscale+alpha or RGBA." }
    }
}

function Get-MaskAndShade([string]$png) {
    if (-not (Test-Path $png)) { throw "Missing content PNG: $png" }
    $info = Get-PngInfo $png
    if (-not $info.HasAlpha) { throw "$png has no alpha channel, but rg8-shade-coverage needs one for coverage." }
    if ($info.Channels -gt 2) {
        Write-Warning "$png has $($info.Channels) channels; the surplus colour is reduced to luminance."
    }
    $bmp = [System.Drawing.Bitmap]::FromFile($png)
    try {
        if ($bmp.Width -ne $bmp.Height) { throw "$png must be square (got $($bmp.Width)x$($bmp.Height))." }
        $size = $bmp.Width
        $rect = New-Object System.Drawing.Rectangle 0, 0, $bmp.Width, $bmp.Height
        $data = $bmp.LockBits($rect, [System.Drawing.Imaging.ImageLockMode]::ReadOnly,
                              [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
        try {
            $stride = $data.Stride
            $buf = New-Object byte[] ($stride * $bmp.Height)
            [System.Runtime.InteropServices.Marshal]::Copy($data.Scan0, $buf, 0, $buf.Length)
            $coverage = New-Object byte[] ($size * $size)
            $shade    = New-Object byte[] ($size * $size)
            for ($y = 0; $y -lt $size; $y++) {
                for ($x = 0; $x -lt $size; $x++) {
                    $o = $y * $stride + $x * 4     # straight (non-premultiplied) BGRA
                    $b = $buf[$o]; $g = $buf[$o + 1]; $r = $buf[$o + 2]
                    $i = $y * $size + $x
                    $coverage[$i] = $buf[$o + 3]
                    $shade[$i] = [byte][math]::Round(0.299 * $r + 0.587 * $g + 0.114 * $b)
                }
            }
            return @{ Size = $size; Coverage = $coverage; Shade = $shade }
        } finally { $bmp.UnlockBits($data) }
    } finally { $bmp.Dispose() }
}

function Add-ByteBlock($sb, [string]$label, [byte[]]$bytes) {
    [void]$sb.AppendLine("  { // $label")
    $line = "    "
    for ($i = 0; $i -lt $bytes.Length; $i++) {
        $line += "$($bytes[$i]),"
        if ($line.Length -ge 110) { [void]$sb.AppendLine($line); $line = "    " }
    }
    if ($line.Trim().Length -gt 0) { [void]$sb.AppendLine($line) }
    [void]$sb.AppendLine("  },")
}

# Entry point. $Sources is an ORDERED list of PNG paths (order == array index order the
# gameplay code expects). Names are supplied by the caller.
function Invoke-CookRg8ShadeCoverage {
    param(
        [string[]]$Sources, [string]$Output,
        [string]$Namespace, [string]$SizeVar, [string]$CoverageVar, [string]$ShadeVar
    )
    $items = @()
    $size = 0
    foreach ($src in $Sources) {
        $m = Get-MaskAndShade $src
        if ($size -eq 0) { $size = $m.Size }
        elseif ($m.Size -ne $size) { throw "All sources must share one resolution; $src is $($m.Size), expected $size." }
        $items += @{ Label = [IO.Path]::GetFileNameWithoutExtension($src); Mask = $m }
        Write-Host "    $($items[-1].Label) : shade + coverage extracted ($size x $size)"
    }
    $n = $items.Count

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("// Generated by Cook/CookRg8ShadeCoverage.ps1 -- do not edit by hand.")
    [void]$sb.AppendLine("// $CoverageVar = silhouette alpha; $ShadeVar = Rec.601 luminance of the source tones.")
    [void]$sb.AppendLine("// Uploaded as an R8G8 texture (R=shade, G=coverage); colour comes from the material tint.")
    [void]$sb.AppendLine("#pragma once")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("namespace $Namespace {")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("constexpr int $SizeVar = $size;  // ${size}x${size}, 1 byte/pixel per channel")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("inline constexpr unsigned char $CoverageVar[$n][$size * $size] = {")
    foreach ($it in $items) { Add-ByteBlock $sb $it.Label $it.Mask.Coverage }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("inline constexpr unsigned char $ShadeVar[$n][$size * $size] = {")
    foreach ($it in $items) { Add-ByteBlock $sb $it.Label $it.Mask.Shade }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("} // namespace $Namespace")

    Set-Content -LiteralPath $Output -Value $sb.ToString() -Encoding ascii
    Write-Host "    wrote $Output"
}
