# Cooker (format "audio"): compress an ORDERED set of 16-bit PCM WAVs into LSF1 blobs and
# emit them as a committed C++ header — a flat byte array (`<Clips>Data`), a parallel
# offset/size table (`<Clips>`), and an index enum. The engine decodes each blob ONCE at load
# (Lur::Audio::DecodeLossless) into PCM the wait-free mixer plays. Game-agnostic: namespace,
# symbol names, and the source order all come from the caller's LUR_COOK declaration.
#
# Unlike the texture cook (pure PowerShell), the compression itself runs in C++: this builds
# Modules/Audio's own codec via Cook/Audio/EncodeSfx.cpp with the host g++ and invokes it, so
# the encoder is LITERALLY the same code as the app's decoder — no chance of drift. That C++
# build only happens when audio content changes on a dev host; the phones compile the
# committed header and never touch g++ or this cooker.
#
# Dot-sourced by Cook/Cook.ps1, which decides WHEN to run it and stamps the source hash.

# Make winget-installed g++ visible even in a fresh shell (same trick as build.ps1).
function Get-HostGxx {
    $env:Path = [System.Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' +
                [System.Environment]::GetEnvironmentVariable('Path', 'User')
    $g = (Get-Command g++ -ErrorAction SilentlyContinue).Source
    if (-not $g) {
        throw "audio cook needs g++ (MinGW-w64) to build the encoder. Install: winget install BrechtSanders.WinLibs.POSIX.UCRT"
    }
    return $g
}

# Build (and cache) the C++ encoder from the engine's own PcmCodec — rebuilt only when its
# sources are newer than the cached exe.
function Ensure-SfxEncoder([string]$Root) {
    $cacheDir = Join-Path $Root '.cache\cook-audio'
    New-Item -ItemType Directory -Force -Path $cacheDir | Out-Null
    $exe   = Join-Path $cacheDir 'encodesfx.exe'
    $enc   = Join-Path $Root 'Cook\Audio\EncodeSfx.cpp'
    $codec = Join-Path $Root 'Modules\Audio\Private\PcmCodec.cpp'
    $inc   = Join-Path $Root 'Modules\Audio\Public'

    $fresh = $false
    if (Test-Path $exe) {
        $exeT = (Get-Item $exe).LastWriteTimeUtc
        $srcT = @((Get-Item $enc).LastWriteTimeUtc, (Get-Item $codec).LastWriteTimeUtc) |
                Sort-Object -Descending | Select-Object -First 1
        if ($exeT -gt $srcT) { $fresh = $true }
    }
    if (-not $fresh) {
        $g = Get-HostGxx
        Write-Host "    building encodesfx (host g++)..."
        & $g -std=c++20 -O2 -I "$inc" "$enc" "$codec" -o "$exe"
        if ($LASTEXITCODE) { throw "encodesfx build failed ($LASTEXITCODE)" }
    }
    return $exe
}

# A file leaf like "move" or "check-soft" -> a C++ identifier "Move" / "CheckSoft".
function ConvertTo-Pascal([string]$name) {
    $parts = $name -split '[^A-Za-z0-9]+' | Where-Object { $_ }
    -join ($parts | ForEach-Object { $_.Substring(0, 1).ToUpper() + $_.Substring(1) })
}

# Append a run of bytes as wrapped `N,` rows (matches the texture cook's ~110-char wrap).
function Add-ByteRun($sb, [byte[]]$bytes) {
    $line = "    "
    for ($i = 0; $i -lt $bytes.Length; $i++) {
        $line += "$($bytes[$i]),"
        if ($line.Length -ge 110) { [void]$sb.AppendLine($line); $line = "    " }
    }
    if ($line.Trim().Length -gt 0) { [void]$sb.AppendLine($line) }
}

# Entry point. $Sources is an ORDERED list of WAV paths (order == enum/table index order the
# gameplay code expects). Names are supplied by the caller (from the LUR_COOK marker).
function Invoke-CookAudio {
    param([string[]]$Sources, [string]$Output, [string]$Namespace, [string]$ClipsVar, [string]$IndexVar)

    $Root = Split-Path -Parent $PSScriptRoot   # Cook/ -> repo root
    $exe = Ensure-SfxEncoder $Root

    $blobs  = @()
    $labels = @()
    foreach ($src in $Sources) {
        if (-not (Test-Path $src)) { throw "Missing SFX WAV: $src" }
        $bin = Join-Path $Root ".cache\cook-audio\$([IO.Path]::GetFileNameWithoutExtension($src)).bin"
        & $exe "$src" "$bin"
        if ($LASTEXITCODE) { throw "encodesfx failed on $src ($LASTEXITCODE)" }
        $bytes = [System.IO.File]::ReadAllBytes($bin)
        $blobs  += , $bytes
        $labels += (ConvertTo-Pascal ([IO.Path]::GetFileNameWithoutExtension($src)))
        Write-Host "    $($labels[-1]) : $($bytes.Length) bytes (LSF1)"
    }

    $n = $blobs.Count
    $total = 0; foreach ($b in $blobs) { $total += $b.Length }

    # Count enum member: "ESfx" -> "SfxCount" (drop a leading E, append Count).
    $countName = $IndexVar
    if ($countName.StartsWith('E')) { $countName = $countName.Substring(1) }
    $countName = "${countName}Count"

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("// Generated by Cook/CookAudio.ps1 -- do not edit by hand.")
    [void]$sb.AppendLine("// LSF1 lossless SFX blobs (mono 16-bit PCM). Decode once at load via")
    [void]$sb.AppendLine("// Lur::Audio::DecodeLossless(${ClipsVar}Data + $ClipsVar[i].Offset, $ClipsVar[i].Size).")
    [void]$sb.AppendLine("#pragma once")
    [void]$sb.AppendLine("#include <cstdint>")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("namespace $Namespace {")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("enum $IndexVar { $($labels -join ', '), $countName };")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("struct SfxBlob { uint32_t Offset; uint32_t Size; };  // into ${ClipsVar}Data[]")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("inline constexpr SfxBlob $ClipsVar[$n] = {")
    $off = 0
    for ($i = 0; $i -lt $n; $i++) {
        [void]$sb.AppendLine("  { $off, $($blobs[$i].Length) },  // $($labels[$i])")
        $off += $blobs[$i].Length
    }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("inline constexpr unsigned char ${ClipsVar}Data[$total] = {")
    for ($i = 0; $i -lt $n; $i++) {
        [void]$sb.AppendLine("  // $($labels[$i])")
        Add-ByteRun $sb $blobs[$i]
    }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("} // namespace $Namespace")

    Set-Content -LiteralPath $Output -Value $sb.ToString() -Encoding ascii
    Write-Host "    wrote $Output ($total bytes across $n clip(s))"
}
