# Generates Games/Chess/Android/app/src/main/cpp/PieceMasks.h from the rhosgfx
# (CC0) piece SVGs in Games/Chess/Content/Pieces/. This is a prototype of the
# LurMotorn asset "cook" pipeline (see the cook GitHub issue): host-side decode
# of Content/ sources into runtime-ready raw bytes, embedded so no image decoder
# ships in the app.
#
# We need a single-channel SILHOUETTE coverage mask per piece TYPE: piece colour
# (white vs black) comes from the material tint at draw time, so 6 masks cover
# all 12 pieces (the "tint trick"). The app ships only raw bytes -- no SVG/PNG
# decoder at runtime.
#
# There is no local SVG rasteriser on the dev host, so this one-time content step
# rasterises each SVG to PNG via the weserv.nl image proxy, then reads the alpha
# channel via System.Drawing. Re-run only when the art or resolution changes.
#
# Usage:  powershell -ExecutionPolicy Bypass -File scripts/gen-piece-masks.ps1 [-Size 96]
param([int]$Size = 96)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$Root      = Split-Path -Parent $PSScriptRoot
$AssetsDir = Join-Path $Root 'Games\Chess\Content\Pieces'
$OutHeader = Join-Path $Root 'Games\Chess\Android\app\src\main\cpp\PieceMasks.h'
$Tmp       = Join-Path $env:TEMP 'lur_piece_raster'
New-Item -ItemType Directory -Force -Path $Tmp | Out-Null
$ua = "LurMotorn/0.1 (johannesdagerbrant@gmail.com)"

# White variants, in Chess::EPieceType order: Pawn, Knight, Bishop, Rook, Queen, King.
$pieces = 'wP','wN','wB','wR','wQ','wK'

# Read one mask (alpha bytes, row-major) from a rasterised PNG.
function Get-AlphaMask([string]$png, [int]$size) {
    $bmp = [System.Drawing.Bitmap]::FromFile($png)
    try {
        $rect = New-Object System.Drawing.Rectangle 0, 0, $bmp.Width, $bmp.Height
        $data = $bmp.LockBits($rect, [System.Drawing.Imaging.ImageLockMode]::ReadOnly,
                              [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
        try {
            $stride = $data.Stride
            $buf = New-Object byte[] ($stride * $bmp.Height)
            [System.Runtime.InteropServices.Marshal]::Copy($data.Scan0, $buf, 0, $buf.Length)
            $mask = New-Object byte[] ($size * $size)
            for ($y = 0; $y -lt $size; $y++) {
                for ($x = 0; $x -lt $size; $x++) {
                    # Format32bppArgb in memory is BGRA; alpha is the 4th byte.
                    $mask[$y * $size + $x] = $buf[$y * $stride + $x * 4 + 3]
                }
            }
            return $mask
        } finally { $bmp.UnlockBits($data) }
    } finally { $bmp.Dispose() }
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// Generated by scripts/gen-piece-masks.ps1 -- do not edit by hand.")
[void]$sb.AppendLine("// Single-channel silhouette coverage masks (one per piece TYPE), extracted")
[void]$sb.AppendLine("// from the rhosgfx (CC0) piece art. Piece colour is the material tint at draw")
[void]$sb.AppendLine("// time, so 6 masks cover all 12 pieces. See Games/Chess/Assets/Pieces/NOTICE.md.")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("namespace ChessArt {")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("constexpr int PieceMaskSize = $Size;  // ${Size}x${Size}, 1 byte/pixel coverage")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("// Indexed by Chess::EPieceType: Pawn, Knight, Bishop, Rook, Queen, King.")
[void]$sb.AppendLine("inline constexpr unsigned char PieceMask[6][$Size * $Size] = {")

foreach ($p in $pieces) {
    $svg = Join-Path $AssetsDir "$p.svg"
    if (-not (Test-Path $svg)) { throw "Missing $svg" }
    $src = "raw.githubusercontent.com/lichess-org/lila/master/public/piece/rhosgfx/$p.svg"
    $url = "https://images.weserv.nl/?url=$([uri]::EscapeDataString($src))&w=$Size&h=$Size&fit=contain&output=png"
    $png = Join-Path $Tmp "$p.png"
    Invoke-WebRequest -Uri $url -OutFile $png -UserAgent $ua -TimeoutSec 30
    $mask = Get-AlphaMask $png $Size

    [void]$sb.AppendLine("  { // $p")
    $line = "    "
    for ($i = 0; $i -lt $mask.Length; $i++) {
        $line += "$($mask[$i]),"
        if ($line.Length -ge 110) { [void]$sb.AppendLine($line); $line = "    " }
    }
    if ($line.Trim().Length -gt 0) { [void]$sb.AppendLine($line) }
    [void]$sb.AppendLine("  },")
    Write-Host "  $p : mask extracted ($Size x $Size)"
}

[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("} // namespace ChessArt")

Set-Content -LiteralPath $OutHeader -Value $sb.ToString() -Encoding ascii
Write-Host "Wrote $OutHeader"