# Generates Games/Chess/Android/app/src/main/cpp/PieceMasks.h from the rhosgfx
# (CC0) piece SVGs in Games/Chess/Content/Pieces/. This is a prototype of the
# LurMotorn asset "cook" pipeline (see the cook GitHub issue): host-side decode
# of Content/ sources into runtime-ready raw bytes, embedded so no image decoder
# ships in the app.
#
# We cook TWO single-byte channels per piece TYPE (see issue #30):
#   * COVERAGE (alpha)   -- the silhouette cutout, straight-alpha composited.
#   * SHADE (luminance)  -- the source art's internal tones (dark outline, cream
#                           body, shadow bands), 0..255.
# Piece colour (white vs black) still comes from the material tint at draw time,
# so 6 mask pairs cover all 12 pieces (the "tint trick"). At draw the shader
# multiplies tint * (shade/255), so the tint supplies the colour while the shade
# preserves the art's tonal detail instead of flattening it to a solid blob. The
# app ships only raw bytes -- no SVG/PNG decoder at runtime.
#
# There is no local SVG rasteriser on the dev host, so this one-time content step
# rasterises each SVG to PNG via the weserv.nl image proxy, then reads the alpha +
# RGB channels via System.Drawing. Re-run only when the art or resolution changes.
#
# Usage:  powershell -ExecutionPolicy Bypass -File scripts/gen-piece-masks.ps1 [-Size 96]
param([int]$Size = 96)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$Root      = Split-Path -Parent $PSScriptRoot
$AssetsDir = Join-Path $Root 'Games\Chess\Content\Pieces'
$OutHeader = Join-Path $Root 'Games\Chess\View\Private\PieceMasks.h'
$Tmp       = Join-Path $env:TEMP 'lur_piece_raster'
New-Item -ItemType Directory -Force -Path $Tmp | Out-Null
$ua = "LurMotorn/0.1 (johannesdagerbrant@gmail.com)"

# White variants, in Chess::EPieceType order: Pawn, Knight, Bishop, Rook, Queen, King.
$pieces = 'wP','wN','wB','wR','wQ','wK'

# Read the coverage (alpha) and shade (Rec.601 luminance) bytes, row-major, from a
# rasterised PNG. Returns a hashtable with .Coverage and .Shade byte arrays.
function Get-MaskAndShade([string]$png, [int]$size) {
    $bmp = [System.Drawing.Bitmap]::FromFile($png)
    try {
        $rect = New-Object System.Drawing.Rectangle 0, 0, $bmp.Width, $bmp.Height
        $data = $bmp.LockBits($rect, [System.Drawing.Imaging.ImageLockMode]::ReadOnly,
                              [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
        try {
            $stride = $data.Stride
            $buf = New-Object byte[] ($stride * $bmp.Height)
            [System.Runtime.InteropServices.Marshal]::Copy($data.Scan0, $buf, 0, $buf.Length)
            $coverage = New-Object byte[] ($size * $size)
            $shade    = New-Object byte[] ($size * $size)
            for ($y = 0; $y -lt $size; $y++) {
                for ($x = 0; $x -lt $size; $x++) {
                    # Format32bppArgb is straight (non-premultiplied) BGRA in memory,
                    # so B,G,R,A are bytes 0..3 and RGB is the true colour even on the
                    # anti-aliased edge (where coverage is partial).
                    $o = $y * $stride + $x * 4
                    $b = $buf[$o]; $g = $buf[$o + 1]; $r = $buf[$o + 2]
                    $i = $y * $size + $x
                    $coverage[$i] = $buf[$o + 3]
                    # Rec.601 luma; the source tones become the tint's shade at draw.
                    $shade[$i] = [byte][math]::Round(0.299 * $r + 0.587 * $g + 0.114 * $b)
                }
            }
            return @{ Coverage = $coverage; Shade = $shade }
        } finally { $bmp.UnlockBits($data) }
    } finally { $bmp.Dispose() }
}

# Emit one `{ ... }` initialiser block of $bytes as a comma-separated C array body.
function Add-ByteBlock($sb, [string]$label, [byte[]]$bytes) {
    [void]$sb.AppendLine("  { // $label")
    $line = "    "
    for ($i = 0; $i -lt $bytes.Length; $i++) {
        $line += "$($bytes[$i]),"
        if ($line.Length -ge 110) { [void]$sb.AppendLine($line); $line = "    " }
    }
    if ($line.Trim().Length -gt 0) { [void]$sb.AppendLine($line) }
    [void]$sb.AppendLine("  },")
}

# Rasterise + extract every piece first, so both arrays can be emitted in order.
$masks = @{}
foreach ($p in $pieces) {
    $svg = Join-Path $AssetsDir "$p.svg"
    if (-not (Test-Path $svg)) { throw "Missing $svg" }
    $src = "raw.githubusercontent.com/lichess-org/lila/master/public/piece/rhosgfx/$p.svg"
    $url = "https://images.weserv.nl/?url=$([uri]::EscapeDataString($src))&w=$Size&h=$Size&fit=contain&output=png"
    $png = Join-Path $Tmp "$p.png"
    Invoke-WebRequest -Uri $url -OutFile $png -UserAgent $ua -TimeoutSec 30
    $masks[$p] = Get-MaskAndShade $png $Size
    Write-Host "  $p : coverage + shade extracted ($Size x $Size)"
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// Generated by scripts/gen-piece-masks.ps1 -- do not edit by hand.")
[void]$sb.AppendLine("// Two single-byte channels per piece TYPE, extracted from the rhosgfx (CC0) art:")
[void]$sb.AppendLine("//   PieceCoverage -- silhouette alpha (straight-alpha cutout).")
[void]$sb.AppendLine("//   PieceShade    -- Rec.601 luminance of the source tones (dark outline, cream")
[void]$sb.AppendLine("//                    body, shadow bands), multiplied by the material tint at draw.")
[void]$sb.AppendLine("// Piece colour (white vs black) is the tint, so 6 pairs cover all 12 pieces; the")
[void]$sb.AppendLine("// shade keeps the art's tonal detail instead of a flat blob (issue #30). Uploaded")
[void]$sb.AppendLine("// as an R8G8 texture (R=shade, G=coverage). See Games/Chess/Content/Pieces/NOTICE.md.")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("namespace ChessArt {")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("constexpr int PieceMaskSize = $Size;  // ${Size}x${Size}, 1 byte/pixel per channel")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("// Both arrays are indexed by Chess::EPieceType: Pawn, Knight, Bishop, Rook, Queen, King.")
[void]$sb.AppendLine("inline constexpr unsigned char PieceCoverage[6][$Size * $Size] = {")
foreach ($p in $pieces) { Add-ByteBlock $sb $p $masks[$p].Coverage }
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("inline constexpr unsigned char PieceShade[6][$Size * $Size] = {")
foreach ($p in $pieces) { Add-ByteBlock $sb $p $masks[$p].Shade }
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("} // namespace ChessArt")

Set-Content -LiteralPath $OutHeader -Value $sb.ToString() -Encoding ascii
Write-Host "Wrote $OutHeader"